### ISSUE TITLE
Unable to get example working in standalone project

### ISSUE THREAD

**Issue by zrachlin** [cjsmith/react-native-connect-iq-mobile-sdk#1]
Hi @cjsmith - thanks for sharing this package!

I was able to clone your repo and get the example app working on my device (successfully sent messages back and forth between my phone and watch), but when I try using the react-native-connect-iq-mobile-sdk in my own react-native project (with identical code in my `App.tsx`, the "Call Get Connected Devices" button brings me to the Garmin Connect app and then back to my app, but doesn't display any connected devices. 

Wondering if you have any suggestions for what I might need to do. Thanks!

Here's the link to my repo: https://github.com/zrachlin/rn-garmin-connect-iq-test

**Comment by zrachlin** [comment]
I actually figured it out by matching your react-native and react versions, and updating the AppDelegate to more closely match yours.

**Comment by cjsmith** [comment]
Glad to hear you figured it out Zach.  I will update the docs to make it clearer that you need to update the AppDelegate .
